baseURL = 'https://denv.it/'
languageCode = 'en-us'
title = '/dev/random'
theme = 'pickles'

[imaging]
resampleFilter = "lanczos"
quality = 80
anchor = "smart"

[imaging.png]
quality = 85

[params]
paginate = 10
twitter="DenysVitali"
# mastodon="@denvit"
author="Denys Vitali"
avatar="https://avatars2.githubusercontent.com/u/4939519?s=460&v=4"
github="denysvitali"
bio="I enjoy writing about technology, with a passion for reverse engineering and software development in Go. I'm always eager to learn new things and am a huge fan of open source software, particularly Kubernetes and cloud-native technologies."
custom_css = ["css/custom.css"]

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3
